#!/bin/bash

[ -z "$1" ] && echo "Please specify snapshot name" && exit 1

[ ! -d ~/.rnode ] && echo "Cannot snapshot: $HOME/.rnode does not exist" && exit 2

! cd "$(dirname "$0")" && echo "Could not cd to script directory" && exit 1

! ./stop-rnode && exit $?

mkdir -p snapshot

TARGET="$PWD/snapshot/$1.tgz"
[ -f "$TARGET" ] && while read -r -p "$TARGET already exists. Replace [y]? " response;do
   if [ "$response" == 'y' ] || [ -z "$response" ]; then
      break
   else
      echo "Aborted"
      exit 0
   fi
done

(cd ~ && tar czf "$TARGET" .rnode)
echo "snapshot created: $TARGET"
