#!/bin/bash

[ -z "$1" ] && echo "Please specify snapshot name" && exit 1

[ ! -d ~/.rnode ] && echo "Cannot snapshot: $HOME/.rnode does not exist" && exit 2

cd `dirname $0`

./stop-rnode
if [ $? -ne 0 ] ; then exit $?; fi

mkdir -p snapshot

TARGET=$PWD/snapshot/$1.tgz
echo $TARGET TARGET
[ -f "$TARGET" ] && while read -p "$TARGET already exists. Replace [y]? " response;do
   if [ "$response" == 'y' ] || [ -z "$response" ]; then
      break
   else
      echo "Aborted"
      exit 0
   fi
done

(cd ~; tar czf "$TARGET" .rnode)
echo "snapshot created: $TARGET"
