#!/bin/bash

! cd "$(dirname "$0")" && echo "$ME: Could not cd to script directory" && exit 1

./run-rnode
./check-rnode
node master-dictionary-setup/deploy-master-dictionary.js
./create-snapshot master-dictionary
