#!/bin/bash

node master-dictionary-setup/clone-rchain-core.js
node master-dictionary-setup/deploy-rchain-core.js
node ./propose.js
node ./create-snapshot.js rchain-core

node master-dictionary-setup/deploy-master-dictionary.js
node ./propose.js
node ./create-snapshot.js master-dictionary

node master-dictionary-setup/deploy-rgov-contracts.js
node ./propose.js
node ./create-snapshot.js rgov
