#!/bin/bash

[ -z "$1" ] && echo "Must specify private key file" && exit 1
[ ! -r "$1" ] && echo "Cannot read $1" && exit 1

private_key=$(cat "$1")

shift

for t in "$@";do
   echo "Deploying $t"
   rnode deploy \
   --valid-after-block-number 0 \
   --phlo-price 1 \
   --phlo-limit 10000000 \
   --private-key "$private_key" \
   "$t" &
done 2>&1
wait
