#!/bin/bash

if ! ./stop-rnode;then
   echo "$0 Aborting"
   exit 1
fi

[ ! -d ~/.rnode ] && echo "
$0: $HOME/.rnode does not exist
Use 'bootstrap' to fix.
" && exit 1

CLASS=`basename $1|sed 's/.rho$//'`
ME=`basename $0`
LOGFILE=$ME.$CLASS.log

DEPLOY="./deploy"

set -x

cd `dirname $0`

private_key=`cat pk.bootstrap`

rnode run -s \
   --validator-private-key $private_key \
   --dev-mode \
   -XX:MaxDirectMemorySize=100m -XX:MaxRAMPercentage=25 \
   > $LOGFILE 2>&1 &

set +x

PID=$!

# The previous command doesn't produce output -- but this makes up for that
tail -f $LOGFILE|sed -e '/Making a transition to Running state./q'

$DEPLOY $1 |tee -a $LOGFILE

# Finalize the rnode
echo "Proposing...." |tee -a $LOGFILE
rnode --grpc-port 40402 propose 2>&1 | tail -n 0 -f $LOGFILE | sed '/Blocks ready to be added/q' 2>&1
echo "Propose finished." |tee -a $LOGFILE

URI=`grep \#define $LOGFILE|tail -1|cut -d' ' -f3|sed 's/]//'`

echo "Generating master directory update."
echo "match [$URI]{[newURI] => {" > generated.$ME.$CLASS.update-directory.rho

cat - >> generated.$ME.$CLASS.update-directory.rho << EOF
new
   lookup(\`rho:registry:lookup\`),
   stdout(\`rho:io:stdout\`),
   deployerId(\`rho:rchain:deployerId\`),
   ch,
   ch1,
   ch2,
   lookCh,
   masterChLookup
EOF
echo "in {" >> generated.$ME.$CLASS.update-directory.rho
cat - >> generated.$ME.$CLASS.update-directory.rho << EOF3
for(@{"read": *read, "write": *write, ..._} <<- @[*deployerId, "MasterContractAdmin"]) {
   stdout!(["read", *read, "write", *write]) |
   read!("$CLASS", *ch) |
   stdout!(["Old class", *ch]) |
   lookup!(newURI, *lookCh) |
   for (C <- lookCh) {
      stdout!(["writing class to dictionary: $CLASS", newURI, *C]) |
      write!("$CLASS", *C, *ch1) |
      for (_ <- ch1) {
         read!("$CLASS", *ch2) |
         stdout!(["Updated value", *ch2])
      }
   }
}}}}
EOF3

$DEPLOY generated.$ME.$CLASS.update-directory.rho

echo "Proposing master directory update...." |tee -a $LOGFILE
rnode --grpc-port 40402 propose 2>&1 | tail -n 0 -f $LOGFILE | sed '/Blocks ready to be added/q' 2>&1

sleep 3 && echo "Stopping deployment rnode" && sleep 3
kill $PID
