#!/bin/bash

[ -z "$1" ] && echo "Please specify snapshot name" && exit 1

[ -d ~/.rnode ] && echo "$HOME/.rnode exists" && while read -r -p "Replace [y]? " response;do
   if [ "$response" != 'y' ] && [ -n "$response" ];then
      echo "Aborted" && exit 0
   else
      break;
   fi
done

! cd "$(dirname "$0")" && echo "Could not cd to script directory" && exit 1

! ./stop-rnode && exit $?

TARGET="$PWD/snapshot/$1.tgz"

if [ -f "$TARGET" ];then
   (cd ~; tar xzf "$TARGET") && echo "snapshot restored: $TARGET"
else
   echo "snapshot not found: $TARGET"
fi
