#!/bin/bash
./stop-rnode

private_key=`cat pk.bootstrap`

cd `dirname $0`

rnode run -s \
   --validator-private-key $private_key \
   --dev-mode \
   -XX:MaxDirectMemorySize=100m -XX:MaxRAMPercentage=25 \
   > run-rnode.log 2>&1 &

tail -F run-rnode.log 2>/dev/null|sed -e '/Making a transition to Running state./q'

stty echo
